# Generated by Django 2.0.5 on 2018-05-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABookGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_text', models.FileField(upload_to='')),
                ('book_name', models.CharField(max_length=127)),
                ('status', models.CharField(choices=[('init', 'Preparing data'), ('generating', 'Generating ABook'), ('error', 'Generation failed'), ('done', 'Generation completed')], default='init', max_length=20)),
                ('generated_file', models.FilePathField()),
                ('lang', models.CharField(choices=[('ru-RU', 'ru-RU'), ('en-EN', 'en-EN'), ('tr-TR', 'tr-TR'), ('uk-UA', 'uk-UA')], default='ru-RU', max_length=10)),
                ('speaker', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('unknown', 'unknown'), ('male', 'male'), ('female', 'female')], default='unknown', max_length=10)),
            ],
        ),
    ]
