# Generated by Django 2.0.5 on 2018-05-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abook_generating', '0002_auto_20180512_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='abookgeneration',
            name='error_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
